name: Test
on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
      - name: Run test suite
        run: |
          cd test
          ./run-tests.sh
